export const ROOT_PAGE_URL = {
  HOME: '/',
  CONTACTUS: '/contact-us',
  CART: '/cart',
  CHECKOUT: '/checkout',
  MYACCOUNT: '/my-account',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOTPASSWORD: '/forgot-password',
  BOOKS: '/books',
  BOOK_DETAIL: '/book-detail',
  ORDERS: '/orders',
  ACCOUNT_DETAILS: '/account-details',
  PAYMENT_METHODS: '/payment-methods',
  CATEGORIES: '/categories',
  USERS: '/users',
};
